name: Publish slides
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Quarto
        uses: quarto-dev/actions/setup@v2
      - name: Publish Quarto
        uses: quarto-dev/actions/publish@v2
        path: _site
