name: Publish slides
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Quarto
        uses: quarto-dev/actions/setup@v2
      - name: Publish Quarto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: quarto-dev/actions/publish@v2
        with:
          target: gh-pages
